
baseURL = "https://playbia.com/"
languageCode = "en-us"
title = "Playbia"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
